# Generated by Django 3.2.5 on 2023-05-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['is_main', 'tag__name']},
        ),
    ]
